### ISSUE TITLE
Error message in IE - unsupported features

### ISSUE THREAD

**Issue by thorild** [OfficeDev/office-js-docs#960] opened 2017-07-04 12:57 UTC
![ie error](https://user-images.githubusercontent.com/16934309/27830889-aee42e5e-60c8-11e7-9b3a-ae107a412a6d.png)

We have started to see an error message in IE11 for the Visio Online integration

BR Fredrik Thorild

**Comment by rahul-mi** [comment] 2017-07-12 09:24
Hi,

This warning should be given only in IE9/10, but not in IE11. The issue is not with Visio Online, but in SPO. The SPO legacy pages are loading in IE10 Compat mode by default, due to which Visio Online is giving warning.
This is fixed now and altough i don't have an exact ETA, but it should reach Production soon.

**Closed** 2017-07-12 14:50 UTC

**Comment by thorild** [comment] 2017-10-24 11:56
Hi

We have some customers that have been reporting this issue again for IE 11. We can get it to disappear with setting  the below to IE=EDGE but then other strange things start to happen with SharePoint such as interacting with file libraries etc

<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
![visio](https://user-images.githubusercontent.com/16934309/31941724-152ef49e-b8c3-11e7-8c9a-582a07cc94f2.png)
@rahul-mi @Lauragra

**Comment by thorild** [comment] 2017-10-24 11:57
![visio](https://user-images.githubusercontent.com/16934309/31941757-369a5150-b8c3-11e7-8ed0-b8aa3a5f65bb.png)

**Comment by rahul-mi** [comment] 2017-10-25 06:29
Hi Fredrik

We are sorry to hear this. I checked internally and found that the fix had to be rolled back due to some other crashes in SharePoint Online. 

The team is actively working to solve this issue soon and we recommend you to use Edge where this issue doesn't happen.

Regards
Rahul Mittal | Program Manager 2 | Microsoft Visio

**Comment by thorild** [comment] 2017-10-25 17:14
Thanks @rahul-mi for the quick reply!

Many of our clients (unfortunately) still use win 7. Would it be possible to include a property in the API such as "obj.hideWarnings= true" or if this is to generic maybe "obj.hideUnsupportedFeaturesWarning = true"?

**Comment by rahul-mi** [comment] 2017-10-29 17:22
Hi @thorild 

We will not be able to provide an API to hide the warning. We understand currently there is a bug due to which the warning is not appearing for the right browsers, but providing an API to hide this warning will just mean that when the bug is fixed also, this API can be used for hiding the warning on unsupported browsers.

Regards
Rahul Mittal | Program Manager 2 | Microsoft Visio

**Comment by thorild** [comment] 2017-11-01 15:36
Hi thanks, do you have any estimated time for when this new fix can reach production.  We have many users on win 7 and IE 11 as well as some others waiting to switch to Visio Online for SPO instead of the legacy web part but we have to keep them on hold. 

I fully understand and I agree regarding the API-fix, it is not a pretty fix to hide the warning but it would certainly have helped at the moment.

**Comment by xandian** [comment] 2018-06-18 09:59
This bug appears to still be in the system, as the yellow bar is very much still visible when using IE 11.

![image](https://user-images.githubusercontent.com/27766499/41529970-03a6a6fe-72ef-11e8-93b7-cde64494ab0c.png)

**Comment by fthorild** [comment] 2018-06-18 10:52
@xandian - they have made a fix for this which I have been able to confirm but we still have problems with sitecollections that were created a while back. If it is possible for your scenario, create a new site collection and check if you have the same error
