### ISSUE TITLE
worksheet Id changing after reopening workbook

### ISSUE THREAD

**Issue by cyberz** [OfficeDev/office-js-docs#297] opened 2016-06-16 10:45 UTC
In my Excel tab-pane addin after adding worksheet(manually/programmatically) and running 

```
Excel.run(function (ctx) {
    var sheet = ctx.workbook.worksheets.getActiveWorksheet().load('name');
          return ctx.sync().then(function () {  
                console.log(sheet);
          });
  });

```

I have worksheet object where id is "{040E0F18-0F61-4CD9-886D-95112C925793}", then I save workbook, close and open again, run code again and it shows me that the worksheet.id now is "{00000000-0001-0000-0000-000000000000}"

**Comment by mlafleur** [comment] 2016-06-16 16:27
There was an issue in the documentation that was recently fixed (PR #271). This is expected behavior. The ID remains constant within a single session but will change between sessions (eg. closing and reopening).

**Comment by cyberz** [comment] 2016-06-16 16:59
@mlafleur, It's a pity. It make using api less useful, because impossible to save settings for specific worksheet. Can you tell why the behavior is designed this way? Thank you!

**Comment by mlafleur** [comment] 2016-06-16 17:11
@cyberz, the original purpose was to provide a way around a user dragging a worksheet around or renaming it and messing up the add-in's workflow. Obviously it would also be valuable in other use cases to have an immutable ID that survives sessions. It is being looked in to for a future release but at the moment there isn't a solid workaround for cross-session tracking of worksheets.

**Comment by taralex77** [comment] 2016-06-16 17:20
If you ask me, looks like someone fixed a bug by changing documentation to declare that it's not a bug :)
The purpose of any ID is to identify something, and this approach fails that purpose miserably.

Is there any other way to store sheet-specific settings? Like DocumentProperties of the Worksheet object when using COM Interop.

**Comment by sumurthy** [comment] 2017-01-13 20:08
Feature 1282441

**Comment by kbrandl** [comment] 2018-11-30 22:44
@cyberz apologies for the lack of engagement on this. We were unable to repro this issue just now. The Office.js API and platform has evolved quite a bit since this issue was opened, so I suspect this may no longer be an issue. I'm going to close this issue, but if you're still having trouble, please feel free to log a new issue in the [OfficeDev/office-js](https://github.com/OfficeDev/office-js) repo, which is monitored by members of the product team.

**Closed by kbrandl** 2018-11-30 22:44 UTC
