### ISSUE TITLE
Opening a link in the docs in "new tab" or "new window" gives Page Not Found error

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#106] opened 2016-03-29 00:22 UTC
It seems that every link in the "new" docs on dev.office.com when attempting to "open in new tab" or "new browser window" results in Page Not Found.

Please don't take away this functionality of the browser for the docs.  Opening every link in the same tab makes reading the docs very difficult.  Please go back to the old way.

Examples
https://dev.office.com/docs/reference/shared/bindings.releasebyidasync.htm
https://dev.office.com/docs/docs/design/add-in-design.htm
...pretty much every link

Thanks.

**Comment by keyur32** [comment] 2016-03-30 03:58
Hi there, sorry for the issue.  You're right it looks to be global issue and the engineering team is working on fixing this scenario up.  As a temporary workaround, if you remove the .htm extension the link will work for you again.  Sorry for the issue.

**Comment by Lauragra** [comment] 2016-04-08 22:39
The issue is fixed now on the live site. Thanks for your feedback!

**Closed by Lauragra** 2016-04-08 22:39 UTC
