### ISSUE TITLE
Internal Server Error when getting values of a huge range in Excel Online using Rich API

### ISSUE THREAD

**Issue by tong-1324** [OfficeDev/office-js-docs#1247] opened 2017-12-08 00:49 UTC
Article: Internal Server Error when getting values of a huge range in Excel Online

Issue: 

You could use the below code to repro the issue, where "Sheet1!A1:A20000" has more than 250 characters in each cell.

```
Excel.run(function (ctx) {
    var sheetName = "Sheet1";
    var rangeAddress = "A1:A20000";
    var range = ctx.workbook.worksheets.getItem(sheetName).getRange(rangeAddress);
    range.load('values');
    return ctx.sync().then(function () {
        console.log(range);
    });
}).catch(function (error) {
    console.log("Error: " + error);
    if (error instanceof OfficeExtension.Error) {
        console.log("Debug info: " + JSON.stringify(error.debugInfo));
    }
});
```

**Comment by Reezaali** [comment] 2017-12-08 00:58
@tong-1324 - Do you have a link to the article that contained this code? 
Thank you!

**Comment by tong-1324** [comment] 2017-12-08 01:02
@Reezaali It's posted at StackOverflow: https://stackoverflow.com/questions/47599608/internal-server-error-when-getting-a-range-values-in-excel-online/47663401#47663401

**Comment by Reezaali** [comment] 2017-12-08 01:11
@tong-1324 Because the issue is already on StackOverflow, and it's not a documentation issue, I'll go ahead and close this issue. If this is a product bug, maybe the issue should be opened on the office-js repo? Feel free to reopen it if I misunderstood the issue. Thanks!

**Closed by Reezaali** 2017-12-08 01:11 UTC
