### ISSUE TITLE
Application Object examples are not related

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#1225] opened 2017-11-23 01:21 UTC
Article:
https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/application.md#suspendapicalculationuntilnextsync

Issue: 
The examples are not related with the API.

**Comment by lindalu-MSFT** [comment] 2017-11-28 22:45
@Hongbo-Miao Can you please provide more information how to fix the issue? Should the examples be updated, replaced, or deleted?

**Comment by Hongbo-Miao** [comment] 2017-11-28 22:49
Someone needs to write a new example.

**Comment by lindalu-MSFT** [comment] 2017-11-29 00:10
Thanks! I hope that "someone" will be @kbrandl or @sumurthy.

**Comment by Hongbo-Miao** [comment] 2017-11-29 00:13
This should not be closed before it has been fixed.

**Comment by lindalu-MSFT** [comment] 2017-11-29 00:17
You're absolutely right, that was an accident! I meant to **Comment**, not **Close and comment**! Thanks for catching this, Hongbo.

**Comment by kbrandl** [comment] 2017-11-29 00:28
Today, Excel reference docs are generated via Sudhi's script -- so we cannot manually fix/update code snippets in the Excel reference docs (any manual changes we make will be overwritten the next time the script runs and rebuilds the docs).  I'd recommend that we postpone addressing this issue, as we are in the process of changing how Reference docs are automatically generated, so Sudhi's script will soon be obsolete.

**Comment by lindalu-MSFT** [comment] 2017-11-29 00:51
Is there a way we can let the customer know?

**Comment by sumurthy** [comment] 2018-01-05 18:07
There is no example for suspendCalc API. I don't know why this is being singled out -- there are 100s of APIs without example. We probably need an example for this in ScriptLab and then the snippet will flow down to specs automatically.

**Comment by kbrandl** [comment] 2018-01-05 18:35
I'll log this issue (i.e., the code snippet shown for this API is not actually related to the API) in VSO.

**Comment by Hongbo-Miao** [comment] 2018-01-05 19:44
Let's not close it until it has been fixed. Thanks

**Comment by kbrandl** [comment] 2018-01-05 19:59
Actually, upon looking at this further -- I agree with @sumurthy's prior comment today that there is no example for the `suspendApiCalculationUntilNextSync` method. 

@Hongbo-Miao -- in the doc that you link to, the **Property access examples** section is a peer of the **suspendApiCalculationUntilNextSync()** section (they are both **H3** headings).  That is, the code sample that you see under the **Property access examples** section is intended to illustrate how to access properties of the `Application` object -- which is in this case, just one property (`calculationMode`) -- it's not intended to show how to use methods such as `suspendApiCalculationUntilNextSync`. 

The same type of **Property access examples** section appears at the end of many API object reference topics, with code samples that illustrate how to access various properties of each object.  For example, here are a few other topics where you'll see the **Property access examples** section:

- https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/worksheet.md
- https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/table.md
- https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/range.md

(Closing this issue, as it's "by design" that the **Property access examples** section does not contain a code sample that shows the `suspendApiCalculationUntilNextSync` method.)

**Closed by kbrandl** 2018-01-05 19:59 UTC
Labels: area: excel, bug: documentation
